routes/web.php
<?php

use App\Http\Controllers\EmployeeController;
use App\Http\Controllers\PositionController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('dashboard');
});
Route::resource('position',PositionController::class);
Route::resource('employee',EmployeeController::class);

app/Models/Employee.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Employee extends Model
{
    use HasFactory;
    protected $fillable = [
        'position_id',
        'nama',
        'nip',
        "tgl_lahir",
        'tahun_lahir',
        'alamat',
        'nomor_hp',
        'agama',
        'foto_ktp',
        'status'
    ];

    /**
     * Get the user that owns the Employee
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function position()
    {
        return $this->belongsTo(Position::class, "position_id", "id");
    }   
}

app/Http/Controllers/EmployeeController.php
<?php

namespace App\Http\Controllers;

use App\Models\Employee;
use App\Models\Position;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Storage;

class EmployeeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if (request()->ajax()) {
            $employee = Employee::with("position")->get();
            return datatables($employee)
                ->addIndexColumn()
                ->addColumn('action', function ($row) {
                    $btn = '<a href="' . route('employee.edit', $row->id) . '" class="edit btn btn-primary btn-sm">Edit</a>';
                    $btn .= '&nbsp;&nbsp;';
                    $btn .= '<a href="' . route('employee.show', $row->id) . '" class="edit btn btn-success btn-sm">Detail</a>';
                    $btn .= '&nbsp;&nbsp;';
                    $btn .= '<button type="button" class="delete deleteData btn btn-danger btn-sm" data-id="' . $row->id . '">Delete</button>';
                    return $btn;
                })
                ->addColumn('status', function ($row) {
                    if ($row->status == 0) {
                        return "Aktif";
                    }
                    else {
                        return "Tidak Aktif";
                    }
                })
                ->rawColumns(['action', 'status'])
                ->toJson();
        }
        return view("employee");
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $position = Position::all();
        $employee = new Employee();
        return view("employee.create", compact(
            "position",
            "employee"
        ));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validate = $this->validate($request, [
            "nama" => "string",
            "nip" => "numeric|unique:employees,nip",
            "nomor_hp" => "numeric",
            "foto_ktp" => "required|mimes:png,jpg"
        ]);

        DB::beginTransaction();
        try {
            $data = $request->all();

            $foto = Storage::disk('public_uploads')->put('img/file_upload', $request->foto_ktp);
            $data['foto_ktp'] = $foto;
    
            $employee = Employee::create($data);
            DB::commit();
            return redirect()->route('employee.index')->with("success", "Berhasil Menambahkan Karyawan");
        } catch (\Throwable $th) {
            DB::rollBack();
            return redirect()->back()->with("danger", "Gagal! Terjadi kesalahan");
        }

    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Employee  $employee
     * @return \Illuminate\Http\Response
     */
    public function show(Employee $employee)
    {
        return view("employee.show", compact(
            "employee"
        ));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Employee  $employee
     * @return \Illuminate\Http\Response
     */
    public function edit(Employee $employee)
    {
        $position = Position::all();
        return view('employee.create', compact(
            "employee",
            "position"
        ));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Employee  $employee
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Employee $employee)
    {
        $validate = $this->validate($request, [
            "nama" => "string",
            "nip" => "unique:employees,nip,".$employee->id,
            "nomor_hp" => "numeric",
            "foto_ktp" => "mimes:png,jpg"
        ]);

        $data = $request->all();
        
        if ($request->foto_ktp) {
            $foto = Storage::disk('public_uploads')->put('img/file_upload', $request->foto_ktp);
            $data['foto_ktp'] = $foto;
        }
        $employee->update($data);
        return redirect()->back()->with("success", "Berhasil Merubah Data Karyawan");
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Employee  $employee
     * @return \Illuminate\Http\Response
     */
    public function destroy(Employee $employee)
    {
        $employee->delete();
        return response()->json(['success'=>'Berhasil Menghapus Karyawan']);
    }
}

resources/views/employee/create.blade.php
@extends('layout.app')

@section('css')
    <link href="{{ asset('vendor/datatables/dataTables.bootstrap4.min.css') }}" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.2.0/css/datepicker.min.css" rel="stylesheet">
@endsection
@section('breadcrumb')
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">Karyawan</h1>
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{ url('/') }}">Dashboard</a></li>
            <li class="breadcrumb-item active" aria-current="page">Tambah Karyawan</li>
        </ol>
    </div>
@endsection
@section('content')
    <div class="card sm mb-4">
        <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
            <h6 class="m-0 font-weight-bold text-primary"></h6>
        </div>
        <div class="card-body">
            <div class="table-responsive p-3">
                @if ($employee->id != null)
                <form action="{{ route('employee.update', $employee->id) }}" method="post" enctype="multipart/form-data">
                    @method("PUT")
                @else
                <form action="{{ route('employee.store') }}" method="post" enctype="multipart/form-data">
                @endif
                    @csrf
                    <div class="row">
                        <div class="col-md">
                            <div class="form-group">
                                <label for="exampleInputEmail1">Nama</label>
                                <input type="text" name="nama" value="{{ old("nama", $employee->nama) }}" class="form-control">
                            </div>
                        </div>
                        <div class="col-md">
                            <div class="form-group">
                                <label for="exampleInputEmail1">NIP</label>
                                <input type="number" name="nip" value="{{ old("nip", $employee->nip) }}" class="form-control">
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="exampleInputEmail1">Jabatan</label>
                        <select name="position_id" class="form-control">
                          <option value="">Pilih Jabatan</option>
                          @foreach ($position as $item)
                              <option value="{{ $item->id }}" {{ old("position_id", $employee->position_id) == $item->id ? "selected" : "" }}>{{ $item->name }}</option>
                          @endforeach
                        </select>
                    </div>
                    <div class="row">
                        <div class="col-md">
                            <div class="form-group">
                                <label for="exampleInputEmail1">Tanggal Lahir</label>
                                <input type="date" value="{{ old("tgl_lahir", $employee->tgl_lahir) }}" name="tgl_lahir" class="form-control">
                            </div>
                        </div>
                        <div class="col-md">
                            <div class="form-group">
                                <label for="exampleInputEmail1">Tahun Lahir</label>
                                <input class="date-own form-control" name="tahun_lahir" value="{{ old("tahun_lahir", $employee->tahun_lahir) }}" type="text">
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md">
                            <div class="form-group">
                                <label for="exampleInputEmail1">No. HP</label>
                                <input type="number" name="nomor_hp" value="{{ old("nomor_hp", $employee->nomor_hp) }}" class="form-control">
                            </div>
                        </div>
                        <div class="col-md">
                            <div class="form-group">
                                <label for="exampleInputEmail1">Alamat</label>
                                <textarea name="alamat" cols="3" rows="3" class="form-control">{{ old("alamat", $employee->alamat) }}</textarea>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                      <div class="col-md">
                        <label for="exampleInputEmail1">Foto KTP</label>
                        <input type="file" name="foto_ktp" class="form-control">
                      </div>
                      <div class="col-md">
                        <label for="exampleInputEmail1">Status</label>
                        <select name="status" class="form-control">
                          <option value="0" {{ old("status", $employee->status) == "0" ? "selected" : "" }}>Aktif</option>
                          <option value="1" {{ old("status", $employee->status) == "1" ? "selected" : "" }}>Tidak Aktif</option>
                        </select>
                      </div>
                      <div class="col-md-2">
                          <div class="form-group">
                              <label for="exampleInputEmail1">Agama</label>
                              <div class="form-check">
                                  <input class="form-check-input" type="radio" name="agama" id="exampleRadios1"
                                      value="islam" {{ old("agama", $employee->agama) == "islam" ? "checked" : "" }}>
                                  <label class="form-check-label" for="exampleRadios1">
                                      Islam
                                  </label>

                                  <input class="form-check-input ml-1" type="radio" name="agama" id="exampleRadios2"
                                      value="kristen" {{ old("agama", $employee->agama) == "kristen" ? "checked" : "" }}>
                                  <label class="form-check-label ml-4" for="exampleRadios2">
                                      Kristen
                                  </label>
                              </div>
                          </div>
                      </div>
                    </div>
                    <br>
                    <button type="submit" class="btn btn-primary">Submit</button>
                </form>
            </div>
        </div>
    </div>
@endsection

@push('js')
    <script src="{{ asset('vendor/datatables/jquery.dataTables.min.js') }}"></script>
    <script src="{{ asset('vendor/datatables/dataTables.bootstrap4.min.js') }}"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
    <script src="https://netdna.bootstrapcdn.com/bootstrap/2.3.2/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.2.0/js/bootstrap-datepicker.min.js"></script>
    <script>
       $('.date-own').datepicker({
        format: "yyyy",
        viewMode: "years", 
        minViewMode: "years",
        autoclose:true //to close picker once year is selected
       });
    </script>
@endpush

resources/views/employee/show.blade.php
@extends('layout.app')

@section('css')
    <link href="{{ asset('vendor/datatables/dataTables.bootstrap4.min.css') }}" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.2.0/css/datepicker.min.css" rel="stylesheet">
@endsection
@section('breadcrumb')
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">Detail Karyawan</h1>
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{ url('/') }}">Dashboard</a></li>
            <li class="breadcrumb-item active" aria-current="page">Detail Karyawan</li>
        </ol>
    </div>
@endsection
@section('content')
    <div class="row">
      <div class="col-md-4">
        <div class="card sm mb-4">
            <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                <h6 class="m-0 font-weight-bold text-primary">Foto KTP</h6>
            </div>
            <div class="card-body">
                <div class="table-responsive p-3">
                  <img class="img-fluid" src="{{ asset("uploads/".$employee->foto_ktp) }}" alt="">
                </div>
            </div>
        </div>
      </div>
      <div class="col-md-8">
        <div class="card sm mb-4">
            <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                <h6 class="m-0 font-weight-bold text-primary">Profile Karyawan</h6>
            </div>
            <div class="card-body">
                <div class="table-responsive p-3">
                  <div class="row">
                    <div class="col">
                      <div class="form-group row">
                        <label for="staticEmail" class="col-sm-2 col-form-label font-weight-bold">Nama</label>
                        <div class="col-sm-10">
                          <label class="form-control-plaintext">{{ $employee->nama }}</label>
                        </div>
                      </div>
    
                      <div class="form-group row">
                        <label for="staticEmail" class="col-sm-2 col-form-label font-weight-bold">NIP</label>
                        <div class="col-sm-10">
                          <label class="form-control-plaintext">{{ $employee->nip }}</label>
                        </div>
                      </div>
    
                      <div class="form-group row">
                        <label for="staticEmail" class="col-sm-2 col-form-label font-weight-bold">Jabatan</label>
                        <div class="col-sm-10">
                          <label class="form-control-plaintext">{{ $employee->position->name }}</label>
                        </div>
                      </div>

                      <div class="form-group row">
                        <label for="staticEmail" class="col-sm-2 col-form-label font-weight-bold">Tanggal Lahir</label>
                        <div class="col-sm-10">
                          <label class="form-control-plaintext">{{ $employee->tgl_lahir }}</label>
                        </div>
                      </div>
    
                      <div class="form-group row">
                        <label for="staticEmail" class="col-sm-2 col-form-label font-weight-bold">Tahun Lahir</label>
                        <div class="col-sm-10">
                          <label class="form-control-plaintext">{{ $employee->tahun_lahir }}</label>
                        </div>
                      </div>
                    </div>


                    <div class="col">
                      <div class="form-group row">
                        <label for="staticEmail" class="col-sm-2 col-form-label font-weight-bold">Agama</label>
                        <div class="col-sm-10">
                          <label class="form-control-plaintext">{{ $employee->agama }}</label>
                        </div>
                      </div>

                      <div class="form-group row">
                        <label for="staticEmail" class="col-sm-2 col-form-label font-weight-bold">Alamat</label>
                        <div class="col-sm-10">
                          <label class="form-control-plaintext">{{ $employee->alamat }}</label>
                        </div>
                      </div>

                      <div class="form-group row">
                        <label for="staticEmail" class="col-sm-2 col-form-label font-weight-bold">Status</label>
                        <div class="col-sm-10">
                          <label class="form-control-plaintext">{{ $employee->status == 0 ? "Aktif" : "Tidak Aktif" }}</label>
                        </div>
                      </div>
                    </div>
                  </div>
                  

                  
                </div>
            </div>
        </div>
      </div>
    </div>
@endsection

@push('js')

@endpush